imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true
doctrine:
    dbal:
        dbname:   '%database_name_test%'
security:
    firewalls:
        # replace 'main' by the name of your own firewall
        main:
            http_basic: ~
hautelook_alice:
    fixtures_path: '/Resources/fixtures/orm' # Path to which to look for fixtures relative to the project directory or the bundle path.

