imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@DefaultBundle/Resources/config/services.yml" }
    - { resource: "@ProductBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: nl
    product_images_directory: '%kernel.root_dir%/../web/img/product'

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
      - 'bootstrap_3_layout.html.twig'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/../var/data/data.sqlite"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

assetic:
  assets:
      jquery:
        inputs:
          - 'js/vendor/jquery-1.12.0.min.js'
      modernizr:
        inputs:
          - 'js/vendor/modernizr-2.8.3.min.js'
      plugins:
        inputs:
          - 'js/plugins.js'
      nivo_slider:
        inputs:
          - 'js/jquery.nivo.slider.pack.js'
      owl_carousel:
        inputs:
          - 'js/owl.carousel.min.js'
      elevate_zoom:
        inputs:
          - 'js/vendor/jquery.ez-plus.js'
      site_js:
        inputs:
          - 'js/bootstrap.min.js'
          - 'js/jquery.nivo.slider.pack.js'
          - 'js/owl.carousel.min.js'
          - 'js/mail.js'
          - 'js/plugins.js'
          - 'js/active.js'
      font_awesome:
        inputs:
          - 'css/font-awesome.min.css'
      bootstrap:
        inputs:
           - 'css/bootstrap.min.css'
      style:
        inputs:
          - 'css/style.css'
      responsive:
        inputs:
          - 'css/responsive.css'
      nivo_slider_css:
        inputs:
          - 'css/nivo-slider.css'
      site_css:
        inputs:
          - 'css/animate.css'
          - 'css/jquery.mb.YTPlayer.min.css'
          - 'css/owl.carousel.css'
          - 'css/owl.theme.css'
          - 'css/owl.transitions.css'
          - 'css/meanmenu.min.css'
          - 'css/jquery-ui.css'
  debug:      '%kernel.debug%'
  use_controller: '%kernel.debug%'
  filters:
    cssrewrite: ~
gregwar_image: ~
knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: 'KnpPaginatorBundle:Pagination:twitter_bootstrap_v3_pagination.html.twig'     # sliding pagination controls template
        sortable: 'KnpPaginatorBundle:Pagination:sortable_link.html.twig' # sort link template
stof_doctrine_extensions:
    default_locale: '%locale%'
    orm:
        default:
            sluggable: true