product_category:
    resource: "@ProductBundle/Controller/ProductCategoryController.php"
    type:     annotation
    prefix:   /

product:
    resource: "@ProductBundle/Controller/BackendProductController.php"
    type:     annotation
    prefix:   /

product_frontend:
    resource: "@ProductBundle/Controller/ProductController.php"
    type:     annotation
    prefix:   /

default:
    resource: "@DefaultBundle/Controller/"
    type:     annotation
    prefix:   /