shopping:
    resource: "@ShoppingBundle/Controller/"
    type:     annotation
    prefix:   /

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

product_category:
    resource: "@ProductBundle/Controller/ProductCategoryController.php"
    type:     annotation
    prefix:   /

product:
    resource: "@ProductBundle/Controller/BackendProductController.php"
    type:     annotation
    prefix:   /

product_frontend:
    resource: "@ProductBundle/Controller/ProductController.php"
    type:     annotation
    prefix:   /

default:
    resource: "@DefaultBundle/Controller/"
    type:     annotation
    prefix:   /

logout:
    path: /logout
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"