# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    twig.extension.text:
       class: Twig_Extensions_Extension_Intl
       tags:
           - { name: twig.extension }
    # default configuration for services in *this* file
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # makes classes in src/ShoppingBundle available to be used as services
    ShoppingBundle\:
        resource: '../../src/ShoppingBundle/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../../src/ShoppingBundle/{Entity,Repository,Tests}'
    # makes classes in src/ProductBundle available to be used as services
    ProductBundle\:
        resource: '../../src/ProductBundle/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../../src/ProductBundle/{Entity,Repository,Tests}'
    # makes classes in src/UserBundle available to be used as services
    UserBundle\:
        resource: '../../src/UserBundle/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../../src/UserBundle/{Entity,Repository,Tests}'
    knp_paginator:
        class: Knp\Component\Pager\Paginator
        public: false
    Knp\Component\Pager\Paginator:
        alias: knp_paginator
        public: false
