<?php

namespace ShoppingBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PurchaseOrderLineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PurchaseOrderLineRepository extends EntityRepository
{
}
