<?php

namespace ShoppingBundle\Repository;

/**
 * PurchaseOrderLineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PurchaseOrderLineRepository extends \Doctrine\ORM\EntityRepository
{
}
