<?php

namespace ProductBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NonUniqueResultException;
use Doctrine\ORM\Query;
use ProductBundle\Entity\ProductCategory;
use ProductBundle\Form\ProductFilterType;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    /**
     * @return int
     * @throws NonUniqueResultException
     */
    public function productsWithoutCategoryCount(): int
    {
        $query = $this->createQueryBuilder('product')
            ->select('count(product.id)')
            ->where('product.category is NULL')
            ->getQuery();

        return $query->getSingleScalarResult();
    }

    /**
     * @return \Doctrine\ORM\Query
     */
    public function productsQuery()
    {
        return $this->createQueryBuilder('product')
            ->getQuery();
    }

    /**
     * @param $amount
     * @return \Doctrine\ORM\Query
     * @throws NonUniqueResultException
     */
    public function randomProductsQuery($amount): Query
    {
        //Get the number of products
        $rows = (int)$this->createQueryBuilder('product')
            ->select('count(product.id)')
            ->getQuery()
            ->getSingleScalarResult();

        $offset = 0;
        if ($rows > $amount) {
            $offset = max(0, mt_rand(0, $rows - $amount - 1));
        }

        return $this->productsQuery()
            ->setMaxResults($amount)
            ->setFirstResult($offset);
    }

    /**
     * @param ProductCategory[] $categories
     * @param int $sort
     * @param bool $other
     * @return \Doctrine\ORM\Query
     */
    public function filteredProducts($categories, int $sort, $other = false): Query
    {
        $query = $this->createQueryBuilder('product')->leftJoin('product.category', 'category');

        $count = 1;
        foreach ($categories as $category) {
            $query->orWhere('category.slug = :slug' . $count)
                ->setParameter('slug' . $count, $category->getSlug());
            $count++;
        }

        if ($other) {
            $query->orWhere('product.category IS NULL');
        }


        if ($sort === ProductFilterType::SORT_PRICE_LOW_TO_HIGH) {
            $query->orderBy('product.price', 'ASC');
        }

        if ($sort === ProductFilterType::SORT_PRICE_HIGH_TO_LOW) {
            $query->orderBy('product.price', 'DESC');
        }

        return $query->getQuery();
    }
}
